POST http://localhost:1234/users
Content-Type: application/json

{
  "user": "fede",
  "password": "prduebasUni4@",
  "email":"admi@gmail.gt",
  "sql": "drop * table"
}

### get users

GET http://localhost:1234/users/af0be6fd-184e-4185-aa48-0f6f4a7c8fed

### update

PUT http://localhost:1234/users/af0be6fd-184e-4185-aa48-0f6f4a7c8fed
Content-Type: application/json

{
  "user": "xjf_2505"
}

### login
POST  http://localhost:1234/verification/login
Content-Type:  application/json

{
  "user":"xjf_255",
  "password": "Juanfher1."
}

### logout

GET http://localhost:1234/verification/logout

### reset login
POST  http://localhost:1234/users/resetLogin
Content-Type:  application/json

{
  "user":"xjf_255"
}