POST http://localhost:1234/users
Content-Type: application/json

{
  "user": "xjf_255",
  "password": "Juanfher1.",
  "email":"juanfher.255@gmail.com",
  "isActive": true,
  "phone": "51450650",
  "sql": "drop * table"
}

### post admin

POST http://localhost:1234/users
Content-Type: application/json

{
  "user": "@dmin",
  "password": "Admin10.",
  "email":"adiazt4@miumg.edu.gt",
  "isActive": true,
  "phone": "53205861",
  "sql": "drop * table"
}

### send friend request

POST http://localhost:1234/user/send-friend-request
Content-Type: application/json

{
  "email":"juanfher.255@gmail.com"
}

### get users

GET http://localhost:1234/users/af0be6fd-184e-4185-aa48-0f6f4a7c8fed

### update

PUT http://localhost:1234/users/af0be6fd-184e-4185-aa48-0f6f4a7c8fed
Content-Type: application/json

{
  "user": "xjf_2505"
}

### login
POST  http://localhost:1234/verification/login
Content-Type:  application/json

{
  "user":"xjf_255",
  "password": "Juanfher1."
}

### logout

GET http://localhost:1234/verification/logout

### reset login
POST  http://localhost:1234/users/resetLogin
Content-Type:  application/json

{
  "user":"xjf_255"
}

### reset login
GET  http://localhost:1234/users/juanfher.255@gmail.co
Content-Type:  application/json

### get friends list
GET http://localhost:1234/friendships/23368730-e585-4bf0-ba13-b2636a1a8027/friends

### get friends request list
GET http://localhost:1234/friendships/23368730-e585-4bf0-ba13-b2636a1a8027/requests

### create friendship request
POST http://localhost:1234/friendships/request
Content-Type: application/json

{
  "addressee": "adiazt4@miumg.edu.gt",
  "requesterId": "2db507e0-2240-4641-91e7-296aadfdfb7a"
}

### accept friendship request
POST http://localhost:1234/friendships/6bcd9a88-7d7e-4217-9aa7-32b40a0fdbd2/accept
Content-Type: application/json

### reject friendship request
POST http://localhost:1234/friendships/b15fd8b3-5f1e-4ed2-84da-cfb3da2768c7/reject
Content-Type: application/json

### remove friendship
DELETE http://localhost:1234/friendships/0609f5e4-1de8-4863-b01e-efaf08b3bd95